### PR TITLE
Fixed breaking unbreakable stuff

### PR DESCRIPTION
**Pull request by Cardinalstars**
This is one solution to the Vajra problem. Looking at the source it's either Modifying the expression value here or instead wrapping the if statement. I'm not a mixin expert and I don't know the best way to do this, so open to suggestions.

Fixes: https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/15439 and possibly more.

Also, this warning is thrown at the beginning of a log in dev even though the .class file looks fine. Not sure what causes that. Don't see it happening when loading in the full pack.
`warning: Unable to locate method mapping for @At(INVOKE.<target>) 'Lnet/minecraft/block/Block;canHarvestBlock(Lnet/minecraft/entity/player/EntityPlayer;I)Z'`

### CODE REVIEW

**Comment by TechnicianLP** [comment]
Ive always assumed this to be a "feature" since bedrock seems to be excluded from the list of breakable blocks.
It would probably be better to expand that blacklist directly.

**Comment by Cardinalstars** [comment]
> Ive always assumed this to be a "feature" since bedrock seems to be excluded from the list of breakable blocks.
> 
> It would probably be better to expand that blacklist directly, if removing that functionality is actually desired.

I'm not sure about this. Unbreakable blocks in many mods are there for a good reason. Warded glass for example becomes useless from the vajra as well as turning the pocket dimension into a free void world. Hard to say I'd like more input from developers though.

**Comment by glowredman** [comment]
Imo this is a design/balancing decision. I tend to favor the proposed solution. The reason being that the GS author probably didn't think about there being more unbreakable blocks. Breaking such blocks is the task of Avaritia's World Breaker.

Regarding the approach: I think using `@ModifyExpressionValue` is a good solution.

**Comment by Dream-Master** [comment]
@Cardinalstars can you resolve the conflict ?

**Review by glowredman — APPROVED** [review]

**Pull request merged**
